name: profesor_oak
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - tensorflow=2.10
  - pip
  - pip:
    - fastapi==0.104.1
    - uvicorn==0.24.0
    - pillow==10.1.0
    - python-multipart==0.0.6
